src/HoneymoonShop/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HoneymoonShop.Data;
using HoneymoonShop.Models;

namespace HoneymoonShop.Controllers
{
    public class BlogsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BlogsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            List<Post> events = _context.Blog.Include(b => b.Posts).Where(b => b.Type.Equals("Evenementen")).First().Posts.Take(2).ToList();
            ViewData["Events"] = events;
            return View(await _context.Blog.ToListAsync());
        }

        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog.SingleOrDefaultAsync(m => m.ID == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Type")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog.SingleOrDefaultAsync(m => m.ID == id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Type")] Blog blog)
        {
            if (id != blog.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog.SingleOrDefaultAsync(m => m.ID == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blog.SingleOrDefaultAsync(m => m.ID == id);
            _context.Blog.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool BlogExists(int id)
        {
            return _context.Blog.Any(e => e.ID == id);
        }
    }
}

src/HoneymoonShop/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HoneymoonShop.Data;
using HoneymoonShop.Models;

namespace HoneymoonShop.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PostsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Posts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Post.Include(p => p.Blog);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post.SingleOrDefaultAsync(m => m.ID == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            ViewData["BlogID"] = new SelectList(_context.Blog, "ID", "ID");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,BlogID,Date,Description")] Post post)
        {
            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["BlogID"] = new SelectList(_context.Blog, "ID", "ID", post.BlogID);
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post.SingleOrDefaultAsync(m => m.ID == id);
            if (post == null)
            {
                return NotFound();
            }
            ViewData["BlogID"] = new SelectList(_context.Blog, "ID", "ID", post.BlogID);
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,BlogID,Date,Description")] Post post)
        {
            if (id != post.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["BlogID"] = new SelectList(_context.Blog, "ID", "ID", post.BlogID);
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post.SingleOrDefaultAsync(m => m.ID == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Post.SingleOrDefaultAsync(m => m.ID == id);
            _context.Post.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PostExists(int id)
        {
            return _context.Post.Any(e => e.ID == id);
        }
    }
}

src/HoneymoonShop/Views/Shared/_BlogPartial.cshtml
@{
    Layout = null;
}
<div class="container containerstyle">
    <div class="row blog-top-picture">
        <div class="blog-top-item img-responsive" style="background:url(/images/web/blog/post1.jpg)">
            <div class="blog-top-block">
                <div class="top-block-header">
                    <div class="block-item-titel">EVENEMENT</div>
                    <div class="block-item-date">
                        <div style="font-size:1.95em">10</div>
                        <div>JAN</div>
                    </div>
                </div>
                <div class="block-item-text">
                    Afgelopen weekend waren wij op de Love & Marriage beurs in Ahoy
                    te Rotterdam. Hier hebben wij de mooiste jurken uit de 2017
                    collectie geshowd.
                </div>
                <div class="block-item-text"><u><a asp-controller="Posts" asp-action="Details/1">Lees meer</a></u> <strong>&#8594;</strong></div>
            </div>
        </div>
        <div class="blog-top-item img-responsive" style="background:url(/images/web/blog/post2.jpg)" >
            <div class="blog-top-block">
                <div class="top-block-header">
                    <div class="block-item-titel">EVENEMENT</div>
                    <div class="block-item-date">
                        <div style="font-size:1.95em">10</div>
                        <div>JAN</div>
                    </div>
                </div>
                <div class="block-item-text">
                    Afgelopen weekend waren wij op de Love & Marriage beurs in Ahoy
                    te Rotterdam. Hier hebben wij de mooiste jurken uit de 2017
                    collectie geshowd.
                </div>
                <div class="block-item-text"><u><a href="http://google.nl">Lees meer</a></u> <strong>&#8594;</strong></div>
            </div>
        </div>
    </div>
</div>
<div class="container padding-box" style="display:flex; flex-direction:column; background:white; padding-top:4.5em;">
    <div class="row">
        <div class="col-md-4 col-xs-12 padding-box-right" style="">
            <div class="box">
                <h4>Veelgestelde vragen</h4>
                <hr>
                <div style="padding-top: 4px">
                    De Honeymoon shop heeft een aantal service punten in Nederland. Hier kun je je bruidskleding laten afspelden en vermaken.
                    <br> lees meer
                </div>
            </div>
            <div class="box">
                <h4>Veelgestelde vragen</h4>
                <hr>
                <div style="padding-top: 4px">
                    De Honeymoon shop heeft een aantal service punten in Nederland. Hier kun je je bruidskleding laten afspelden en vermaken.
                    <br> lees meer
                </div>
            </div>
            <div class="box">
                <h4>Veelgestelde vragen</h4>
                <hr>
                <div style="padding-top: 4px">
                    De Honeymoon shop heeft een aantal service punten in Nederland. Hier kun je je bruidskleding laten afspelden en vermaken.
                    <br> lees meer
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xs-12 padding-box-right">
            <div class="box">
                <h4>Veelgestelde vragen</h4>
                <hr>
                <div style="padding-top: 4px">
                    De Honeymoon shop heeft een aantal service punten in Nederland. Hier kun je je bruidskleding laten afspelden en vermaken.
                    <br> lees meer
                </div>
            </div>
            <div class="box text-uppercase" style="background:#cce7d4">
                <b>Schrijf je in voor onze nieuwsbrief</b>
            </div>
            <div class="box">
                <h4>Veelgestelde vragen</h4>
                <hr>
                <div style="padding-top: 4px">
                    De Honeymoon shop heeft een aantal service punten in Nederland. Hier kun je je bruidskleding laten afspelden en vermaken.
                    <br> lees meer
                </div>
            </div>
            <div class="box">
                <h4>Veelgestelde vragen</h4>
                <hr>
                <div style="padding-top: 4px">
                    De Honeymoon shop heeft een aantal service punten in Nederland. Hier kun je je bruidskleding laten afspelden en vermaken.
                    <br> lees meer
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xs-12">
            <div class="box">
                <h4>Veelgestelde vragen</h4>
                <hr>
                <div style="padding-top: 4px">
                    De Honeymoon shop heeft een aantal service punten in Nederland. Hier kun je je bruidskleding laten afspelden en vermaken.
                    <br> lees meer
                </div>
            </div>
            <div class="box">
                <h4>Veelgestelde vragen</h4>
                <hr>
                <div style="padding-top: 4px">
                    De Honeymoon shop heeft een aantal service punten in Nederland. Hier kun je je bruidskleding laten afspelden en vermaken.
                    <br> lees meer
                </div>
            </div>
            <div class="box text-uppercase" style="background:#f0597c; color:white">
                <b>Wij zijn opzoek naar een verkoop styliste</b>
            </div>
            <div class="box">
                <h4>Veelgestelde vragen</h4>
                <hr>
                <div style="padding-top: 4px">
                    De Honeymoon shop heeft een aantal service punten in Nederland. Hier kun je je bruidskleding laten afspelden en vermaken.
                    <br> lees meer
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-xs-12" style="text-align:center">
            <button class="btn btn-default primary-button index-button" type="button" style="border-width:6px; border-radius:0%"><b>MEER BERICHTEN</b></button>
        </div>
    </div>
    <div class="row" style="padding-top:2em">
        <div class="col-md-12 col-xs-12" style="text-align:center">
            <p> <b style="color:#f0597c; font-size:2em">▼</b> </p>
        </div>
    </div>
</div>

src/HoneymoonShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA_Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, inital-scale=1">
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <script src="~/js/jquery-3.1.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/header.css" rel="stylesheet">
    <link href="~/css/footer.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cookie|Lato" rel="stylesheet">
    <title>@ViewData["Title"] - HoneymoonShop</title>
    @RenderSection("Imports", required: false)
</head>
<body>
    <div class="container" style="background:@ViewData["Background"]; height:@ViewData["HeaderHeight"]; background-size: 100% 100%;">
        <div class="container-fluid navbar-pink" style="padding:0; margin-left: -1.1%;">
            <div class="row disappear-xs" style="height:100%">
                <div class="max-height-center col-lg-1 col-md-2 col-sm-2 col-xs-12" style="margin-top: 1.5em; margin-bottom: 1.5em; padding-top:0%;"><a asp-controller="Home" asp-action="Index"><b id="website">WEBSITE</b></a></div>
                <div class="max-height-center col-lg-1 col-md-1 col-sm-1 col-xs-12" style="margin-top: 1.5em; margin-bottom: 1.5em; padding-top:0%;"><a asp-controller="Dresses" asp-action="Overview" style="color:#f0577a"><b id="webshop">WEBSHOP</b></a></div>
                <div class="max-height-center col-lg-4 col-md-4 col-sm-2 col-xs-12 nopad-xs"></div>
                <div id="tel" class="max-height-center col-lg-offset-1 col-lg-2 col-md-2 col-sm-3 col-xs-12" style="text-align: right; margin-top: 1.5em; margin-bottom: 1.5em; padding-top:0%;"><b>T</b>(010) 4126143</div>
                <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12" style="background: white; width: 270px; float: right; padding-top: 0.67em; padding-bottom: .67em;">
                    <div class="input-group search">
                        <input id="searchfield" type="text" class="form-control" placeholder="Wat zoek je?" style="height: 100%;margin-top: .5em;"> <span class="input-group-btn">
                            <button id="searchbutton" class="btn btn-default primary-button" type="button" style="background-color: white; height:3.1em; width: 3.1em"> <span class="glyphicon glyphicon-search" aria-hidden="true" style="color: black"></span> </button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="dropdown show-sm">
            <a asp-controller="Home" asp-action="Index" id="dropdownMenu" class="btn btn-default dropdown-toggle primary-button index-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="background:none"> <b>HONEYMOON SHOP</b> <span class="caret"></span> </a>
            <ul class="dropdown-menu tablet-fsize" style="background:none" aria-labelledby="dropdown">
                <li><a style="color: #f0577a" asp-controller="Home" asp-action="Index"><b>HOME</b></a></li>
                <li><a asp-controller="Dresses" asp-action="Index"><b>BRUID</b></a></li>
                <li><a href="#"><b>BRUIDEGOM</b></a></li>
                <li><a asp-controller="Home" asp-action="About"><b>DE WINKEL</b></a></li>
                <li><a asp-controller="Blogs" asp-action="Index"><b>BLOG</b></a></li>
                <li><a asp-controller="Home" asp-action="Contact"><b>CONTACT</b></a></li>
                <li><a asp-controller="Appointments" asp-action="Create"><b>AFSPRAAK MAKEN</b></a></li>
            </ul>
        </div>
        <div class="container-fluid" style="padding: 0; padding-top: 1em">
            <nav class="navbar navbar-default navbar-transparent">
                <div class="container-fluid hide-sm">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapseNav"> <span class="sr-only">Toggle Navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button> <a class="navbar-brand" asp-controller="Home" asp-action="Index"><b>HONEYMOON SHOP</b></a>
                    </div>
                    <div class="collapse navbar-collapse" id="collapseNav">
                        <ul class="nav navbar-nav navbar-right thinner-xs scale-nav">
                            <li><a style="color: #f0577a" asp-controller="Home" asp-action="Index"><b>HOME</b></a></li>
                            <li><a asp-controller="Dresses" asp-action="Index"><b>BRUID</b></a></li>
                            <li><a href="#"><b>BRUIDEGOM</b></a></li>
                            <li><a asp-controller="Home" asp-action="About"><b>DE WINKEL</b></a></li>
                            <li><a asp-controller="Blogs" asp-action="Index"><b>BLOG</b></a></li>
                            <li><a asp-controller="Home" asp-action="Contact"><b>CONTACT</b></a></li>
                            <li>
                                
                                <form class="navbar-form navbar-left">
                                    <div class="input-group">
                                        <a asp-controller="Appointments" asp-action="Create" class="btn btn-default primary-button" style="color:white"><b>AFSPRAAK MAKEN</b></a>
                                    </div>
                                </form>
                            </li>
                        </ul>
                        <ul class="appear-xs nav navbar-nav thinner-xs">
                            <li><a href="#"><b>WEBSITE</b></a></li>
                            <li><a href="#"><b>WEBSHOP</b></a></li>
                            <li><b>T</b> (010) 4126143 </li>
                            <li>
                                <form class="navbar-form navbar-right" style="margin-top: 0; padding: 0; margin-bottom: 0">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Wat zoek je?" style="height: 3.1em;"> <span class="input-group-btn">
                                            <button class="btn btn-default primary-button" type="button" style="background-color: white; height:3.1em; width: 3.1em"> <span class="glyphicon glyphicon-search" aria-hidden="true" style="color: black"></span> </button>
                                        </span>
                                    </div>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        @RenderSection("HeaderOverlay", required: false)
    </div>
    @RenderBody()
    <hr>
    <footer class="container">
        <br> <br> <br>
        <div class="row fullrow" style="display:flex; flex-wrap: wrap;">
            <a id="link-pasafspraak" class="footer-img" href="http://google.nl">
                <div class="col-md-4 footer-box">
                    <p class="">Afspraak</p>
                    <p class="">  <b>MAAK EEN <br>PASAFSPRAAK</b></p>
                </div>
            </a>
            <a id="link-social" class="footer-img" href="http://google.nl">
                <div class="col-md-4 footer-box" >
                    <p class="">Social</p>
                    <p class="">  <b>VOLG ONS</b></p>
                    <img src="~/images/web/deel-dit.png" width="214" height="57" border="0" usemap="#map" class="img-responsive deel-dit" />
                    <map name="map">
                        <area shape="rect" coords="1,1,46,57" alt="facebook" href="http://facebook.com" />
                        <area shape="rect" coords="47,2,91,55" alt="twitter" href="http://twitter.com" />
                        <area shape="rect" coords="93,1,131,55" alt="pinterest" href="http://pinterest.com" />
                        <area shape="rect" coords="132,2,167,57" alt="youtube" href="http://youtube.com" />
                        <area shape="rect" coords="167,1,213,58" alt="instagram" href="http://instagram.com" />
                    </map>
                </div>
            </a>
            <a id="link-review" class="footer-img" href="http://google.nl">
                <div class="col-md-4 footer-box" >
                    <p class="">Reviews</p>
                    <p class="">  <b>BEKIJK ONZE<br /> REVIEWS</b></p>
                </div>
            </a>
        </div>
        <div class="row fullrow">
            <p class="info-txt"> Korte Hoogstraat 4, 3011 Rotterdam &emsp;<b>email</b> info@honeymoonshop.nl&emsp;<b>tel </b>(010) 412 61 43&emsp;<b>whatsapp</b>  (06)25 19 99 27<br> <b>Openingstijden&emsp;MA</b>12.00-17.30&emsp;<b>DI t/m VR</b> 09.30-17.30 <b>ZA&emsp;</b> 09.30-18.00&emsp;<b>DI t/m VR</b> 09.30-17.30  </p>
        </div>
        <div class="row">
            <br> <br><br>
            <img src="~/images/web/grand-weddingshow.png" alt="grand weddingprize icon" class="weddingshow img-responsive" />
        </div>
        <div class="row list1 align-sm">
            <br> <br><br>
            <br><br>
            <div class="col-md-3 col-sm-5 col-sm-offset-3 col-lg-offset-0 col-md-offset-0">
                <ul class="list-group list-nopadbot">
                    <li class="list-group-item txt1" style="color:#f0597c"><b>WINKEL</b></li>
                    <li class="list-group-item"><a href="#">Over de Honeymoon shop</a></li>
                    <li class="list-group-item"><a href="#">Servicepunten</a></li>
                    <li class="list-group-item"><a href="#">Routebeschrijving</a></li>
                    <li class="list-group-item"><a href="#">Beurzen en evenementen</a></li>
                    <li class="list-group-item"><a href="#">Vacatures</a></li>
                    <li class="list-group-item"><a href="#">Verkoopvoorwaarden</a></li>
                    <li class="list-group-item"><a href="#">CBW erkend</a></li>
                    <li class="list-group-item"><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-5 box-offset">
                <ul class="list-group list-nopadbot">
                    <li class="list-group-item" style="color:#f0597c"><b>SERVICE</b></li>
                    <li class="list-group-item"><a href="#">Beoordelingen</a></li>
                    <li class="list-group-item"><a href="#">Dressfinder</a></li>
                    <li class="list-group-item"><a href="#">Gratis trouwmagazine</a></li>
                    <li class="list-group-item"><a href="#">Niewsbrief</a></li>
                    <li class="list-group-item"><a href="#">Veel gestelde vragen</a></li>
                    <li class="list-group-item"><a href="#">CBW erkend</a></li>
                    <li class="list-group-item"><a href="#">Reinigen van je trouwjurk</a></li>
                    <li class="list-group-item"><a href="#">10 redenen om je afspraak te maken</a></li>
                    <li class="list-group-item"><a href="#">The Perfect Match</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-4 box-offset2">
                <ul class="list-group list-nopadbot">
                    <li class="list-group-item" style="color:#f0597c"><b>ACTIES</b></li>
                    <li class="list-group-item"><a href="#">The Grand Wedding Show</a></li>
                    <li class="list-group-item"><a href="#">Summer Sale</a></li>
                    <li class="list-group-item"><a href="#">Trouwjurken onder de 1000 euro</a></li>
                    <li class="list-group-item"><a href="#">Trouwjurken voor de volslanke bruid</a></li>
                </ul>
            </div>
        </div>

    </footer>
    @RenderSection("scripts", required: false)
</body>
</html>